export enum AssetType {
  UNSPECIFIED = 'ASSET_TYPE_UNSPECIFIED',
  CRYPTOCURRENCY = 'ASSET_TYPE_CRYPTOCURRENCY',
  STOCK = 'ASSET_TYPE_STOCK',
  BOND = 'ASSET_TYPE_BOND',
  COMMODITY = 'ASSET_TYPE_COMMODITY',
  FOREX = 'ASSET_TYPE_FOREX',
  FUND = 'ASSET_TYPE_FUND',
}

export enum AccountType {
  UNSPECIFIED = 'ACCOUNT_TYPE_UNSPECIFIED',
  WALLET = 'ACCOUNT_TYPE_WALLET',
  EXCHANGE = 'ACCOUNT_TYPE_EXCHANGE',
  BANK = 'ACCOUNT_TYPE_BANK',
  BROKER = 'ACCOUNT_TYPE_BROKER',
}

export enum RuleStatus {
  UNKNOWN = 'RULE_STATUS_UNKNOWN',
  ACTIVE = 'RULE_STATUS_ACTIVE',
  PAUSED = 'RULE_STATUS_PAUSED',
  DISABLED = 'RULE_STATUS_DISABLED',
  ERROR = 'RULE_STATUS_ERROR',
}

export enum ExecutionStatus {
  UNKNOWN = 'EXECUTION_STATUS_UNKNOWN',
  PENDING = 'EXECUTION_STATUS_PENDING',
  IN_PROGRESS = 'EXECUTION_STATUS_IN_PROGRESS',
  COMPLETED = 'EXECUTION_STATUS_COMPLETED',
  FAILED = 'EXECUTION_STATUS_FAILED',
  CANCELLED = 'EXECUTION_STATUS_CANCELLED',
}

export enum TransactionType {
  UNSPECIFIED = 'TRANSACTION_TYPE_UNSPECIFIED',
  BUY = 'TRANSACTION_TYPE_BUY',
  SELL = 'TRANSACTION_TYPE_SELL',
  TRANSFER_IN = 'TRANSACTION_TYPE_TRANSFER_IN',
  TRANSFER_OUT = 'TRANSACTION_TYPE_TRANSFER_OUT',
  DEPOSIT = 'TRANSACTION_TYPE_DEPOSIT',
  WITHDRAWAL = 'TRANSACTION_TYPE_WITHDRAWAL',
  FEE = 'TRANSACTION_TYPE_FEE',
}

export enum TransactionStatus {
  UNKNOWN = 'TRANSACTION_STATUS_UNKNOWN',
  PENDING = 'TRANSACTION_STATUS_PENDING',
  CONFIRMED = 'TRANSACTION_STATUS_CONFIRMED',
  FAILED = 'TRANSACTION_STATUS_FAILED',
}

// UI-specific enums
export enum TimeRange {
  HOUR_24 = '24h',
  WEEK_1 = '7d',
  MONTH_1 = '30d',
  MONTH_3 = '90d',
  YEAR_1 = '1y',
  ALL = 'all',
}
